eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8083
spring:
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true  #配置可以存在多个生产者实例
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
feign:
  hystrix:
    enabled: true  #配置文件中配置打开断路器
ribbon:
  eureka:
    enabled: true

